// Packages/com.spiralingstudio.mcp.vfxgraph/Editor/Generation/Emitters/CatalogEmitter.cs
// Phase 2 task 9: emits Editor/Generated/VfxCatalog.g.cs — the name-resolution
// table and static arrays backing the vfx_diag.list_* tools.
// Output is deterministic: same CatalogIR always produces byte-identical text.
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SpiralingStudio.VfxMcp.Generation
{
    /// <summary>
    /// Emits VfxCatalog.g.cs. All collections are sorted deterministically
    /// (StringComparer.Ordinal), short-name collisions are deduplicated per
    /// erratum P-M1, and collisions are surfaced in a dedicated Collisions
    /// table for the override layer + vfx_diag.list_collisions.
    /// </summary>
    internal sealed class CatalogEmitter
    {
        public string Emit(CatalogIR ir)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Do not edit. Regenerate via Tools/VFX MCP/Regenerate Catalog.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace SpiralingStudio.VfxMcp.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class VfxCatalog");
            sb.AppendLine("    {");
            sb.AppendLine($"        public const string PackageVersion = \"{ir.VfxGraphPackageVersion}\";");
            sb.AppendLine();

            EmitArray(sb, "Operators", ir.Operators.Select(o => o.TypeFQN));
            EmitArray(sb, "Blocks", ir.Blocks.Select(o => o.TypeFQN));
            EmitArray(sb, "Contexts", ir.Contexts.Select(o => o.TypeFQN));
            EmitArray(sb, "Parameters", ir.Parameters.Select(o => o.TypeFQN));
            EmitArray(sb, "SubgraphOperators", ir.SubgraphOperators.Select(o => o.TypeFQN));
            EmitArray(sb, "SubgraphBlocks", ir.SubgraphBlocks.Select(o => o.TypeFQN));
            EmitArray(sb, "SubgraphContexts", ir.SubgraphContexts.Select(o => o.TypeFQN));

            // ERRATUM P-M1: deduplicate short names to avoid dictionary
            // ArgumentException at runtime on collision. Collisions are
            // recorded into a separate Collisions table for the override
            // layer and vfx_diag.list_collisions.
            sb.AppendLine("        public static readonly System.Collections.Generic.Dictionary<string, string> ShortNameToFqn = new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.OrdinalIgnoreCase)");
            sb.AppendLine("        {");
            var allNodes = ir.Operators
                .Concat(ir.Blocks)
                .Concat(ir.Contexts)
                .Concat(ir.Parameters)
                .Concat(ir.SubgraphOperators)
                .Concat(ir.SubgraphBlocks)
                .Concat(ir.SubgraphContexts)
                .OrderBy(n => n.TypeFQN, System.StringComparer.Ordinal)
                .ToList();
            var seen = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
            var collisions = new Dictionary<string, List<string>>(System.StringComparer.OrdinalIgnoreCase);
            foreach (var node in allNodes)
            {
                if (!seen.Add(node.ShortName))
                {
                    if (!collisions.TryGetValue(node.ShortName, out var list))
                        collisions[node.ShortName] = list = new List<string>();
                    list.Add(node.TypeFQN);
                    sb.AppendLine($"            // collision (resolved in Quirks.yaml): {node.ShortName} -> {node.TypeFQN}");
                    continue;
                }
                sb.AppendLine($"            {{ \"{node.ShortName}\", \"{node.TypeFQN}\" }},");
            }
            sb.AppendLine("        };");
            sb.AppendLine();

            // Emit the Collisions table (sorted deterministically by short name).
            sb.AppendLine("        public static readonly System.Collections.Generic.Dictionary<string, string[]> Collisions = new System.Collections.Generic.Dictionary<string, string[]>(System.StringComparer.OrdinalIgnoreCase)");
            sb.AppendLine("        {");
            foreach (var kv in collisions.OrderBy(k => k.Key, System.StringComparer.Ordinal))
            {
                var fqns = string.Join(", ", kv.Value
                    .OrderBy(f => f, System.StringComparer.Ordinal)
                    .Select(f => $"\"{f}\""));
                sb.AppendLine($"            {{ \"{kv.Key}\", new string[] {{ {fqns} }} }},");
            }
            sb.AppendLine("        };");

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void EmitArray(StringBuilder sb, string name, IEnumerable<string> items)
        {
            sb.AppendLine($"        public static readonly string[] {name} = new string[]");
            sb.AppendLine("        {");
            foreach (var item in items.OrderBy(s => s, System.StringComparer.Ordinal))
                sb.AppendLine($"            \"{item}\",");
            sb.AppendLine("        };");
            sb.AppendLine();
        }
    }
}
