// Packages/com.spiralingstudio.mcp.vfxgraph/Editor/Generation/Emitters/CoercersEmitter.cs
// Phase 3 task 3A-3: emits Editor/Generated/VfxCoercers.g.cs.
//
// Hand-written leaf coercers (float / int / bool / string / textures /
// graphics buffer) plus generated compound coercers per
// SlotTypeDescriptor.IsCompound entry. Compound coercers dispatch each child
// to the appropriate sibling coercer per erratum P-M2 (no hardcoded
// CoerceToFloat). Compound types are emitted in topological order so a
// nested type's dependency is always defined before its consumer
// (Kahn's algorithm).
//
// Output is deterministic: identical input IR → identical text bytes.
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SpiralingStudio.VfxMcp.Generation
{
    internal sealed class CoercersEmitter
    {
        // Set of leaf coercer method names that EmitLeafCoercers always emits.
        // Used by DispatchCoercer to know which child types are addressable
        // without dropping back to the compound table.
        private static readonly HashSet<string> KnownLeafTypes = new HashSet<string>(System.StringComparer.Ordinal)
        {
            "System.Single", "System.Double", "System.Int32", "System.UInt32",
            "System.Boolean", "System.String",
            "UnityEngine.Texture2D", "UnityEngine.Texture3D", "UnityEngine.Cubemap",
            "UnityEngine.Mesh", "UnityEngine.GraphicsBuffer",
            "UnityEngine.AnimationCurve", "UnityEngine.Gradient",
            "UnityEngine.Matrix4x4",
        };

        public string Emit(CatalogIR ir)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Do not edit. Regenerate via Tools/VFX MCP/Regenerate Catalog.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using Newtonsoft.Json.Linq;");
            sb.AppendLine("using UnityEditor;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace SpiralingStudio.VfxMcp.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class VfxCoercers");
            sb.AppendLine("    {");

            EmitLeafCoercers(sb);

            // Topologically sort compound slot types so nested-compound
            // dependencies emit BEFORE their consumers. Kahn's algorithm.
            var compounds = ir.SlotTypes
                .Where(s => s.IsCompound)
                .OrderBy(s => s.TypeFQN, System.StringComparer.Ordinal)
                .ToList();
            var ordered = TopologicalSort(compounds);

            // Build the set of compound type FQNs that we will emit; the
            // dispatch fallback uses it to emit a "default(T)" stub for child
            // types that have no resolvable coercer (e.g. structs whose only
            // fields are private and never appear in CatalogIR).
            var emittedCompoundFqns = new HashSet<string>(
                ordered.Select(c => c.TypeFQN), System.StringComparer.Ordinal);

            foreach (var slot in ordered)
                EmitCompoundCoercer(sb, slot, emittedCompoundFqns);

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // ─────────────────────────── topological sort ───────────────────────────
        // Each compound C depends on every child whose ChildTypeFQN is itself a
        // compound. We order C strictly after every dependency is emitted.
        private static List<SlotTypeDescriptor> TopologicalSort(List<SlotTypeDescriptor> compounds)
        {
            var byFqn = new Dictionary<string, SlotTypeDescriptor>(System.StringComparer.Ordinal);
            foreach (var c in compounds) byFqn[c.TypeFQN] = c;

            var visited = new HashSet<string>(System.StringComparer.Ordinal);
            var visiting = new HashSet<string>(System.StringComparer.Ordinal);
            var ordered = new List<SlotTypeDescriptor>();

            void Visit(SlotTypeDescriptor node)
            {
                if (visited.Contains(node.TypeFQN)) return;
                if (!visiting.Add(node.TypeFQN))
                    return; // cycle — break it; emission still safe due to forward decls.

                foreach (var child in node.Children)
                {
                    if (byFqn.TryGetValue(child.ChildTypeFQN, out var dep))
                        Visit(dep);
                }
                visiting.Remove(node.TypeFQN);
                visited.Add(node.TypeFQN);
                ordered.Add(node);
            }

            foreach (var c in compounds) Visit(c);
            return ordered;
        }

        // ─────────────────────────── leaf coercers ───────────────────────────
        // These are always present regardless of CatalogIR contents because the
        // compound coercers always dispatch to them via DispatchCoercer().
        private static void EmitLeafCoercers(StringBuilder sb)
        {
            sb.AppendLine("        public static float CoerceToFloat(JToken t)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (t == null) throw new System.ArgumentNullException(nameof(t));");
            sb.AppendLine("            if (t.Type == JTokenType.Float || t.Type == JTokenType.Integer) return t.Value<float>();");
            sb.AppendLine("            throw new System.InvalidCastException($\"Cannot coerce {t.Type} to float\");");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static int CoerceToInt(JToken t)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (t == null) throw new System.ArgumentNullException(nameof(t));");
            sb.AppendLine("            if (t.Type == JTokenType.Integer || t.Type == JTokenType.Float) return t.Value<int>();");
            sb.AppendLine("            throw new System.InvalidCastException($\"Cannot coerce {t.Type} to int\");");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static uint CoerceToUInt(JToken t)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (t == null) throw new System.ArgumentNullException(nameof(t));");
            sb.AppendLine("            if (t.Type == JTokenType.Integer || t.Type == JTokenType.Float) return t.Value<uint>();");
            sb.AppendLine("            throw new System.InvalidCastException($\"Cannot coerce {t.Type} to uint\");");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static bool CoerceToBool(JToken t)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (t == null) throw new System.ArgumentNullException(nameof(t));");
            sb.AppendLine("            if (t.Type == JTokenType.Boolean) return t.Value<bool>();");
            sb.AppendLine("            throw new System.InvalidCastException($\"Cannot coerce {t.Type} to bool\");");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static string CoerceToString(JToken t)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (t == null) return null;");
            sb.AppendLine("            return t.Value<string>();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static Texture2D CoerceToTexture2D(JToken t)");
            sb.AppendLine("        {");
            sb.AppendLine("            var path = t?.Value<string>();");
            sb.AppendLine("            if (string.IsNullOrEmpty(path))");
            sb.AppendLine("                throw new System.ArgumentException(\"Texture2D requires an asset path string.\");");
            sb.AppendLine("            var tex = AssetDatabase.LoadAssetAtPath<Texture2D>(path);");
            sb.AppendLine("            if (tex == null)");
            sb.AppendLine("                throw new System.IO.FileNotFoundException($\"Texture not found at {path}\");");
            sb.AppendLine("            return tex;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static Texture3D CoerceToTexture3D(JToken t)");
            sb.AppendLine("        {");
            sb.AppendLine("            var path = t?.Value<string>();");
            sb.AppendLine("            if (string.IsNullOrEmpty(path))");
            sb.AppendLine("                throw new System.ArgumentException(\"Texture3D requires an asset path string.\");");
            sb.AppendLine("            return AssetDatabase.LoadAssetAtPath<Texture3D>(path);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static Cubemap CoerceToCubemap(JToken t)");
            sb.AppendLine("        {");
            sb.AppendLine("            var path = t?.Value<string>();");
            sb.AppendLine("            if (string.IsNullOrEmpty(path))");
            sb.AppendLine("                throw new System.ArgumentException(\"Cubemap requires an asset path string.\");");
            sb.AppendLine("            return AssetDatabase.LoadAssetAtPath<Cubemap>(path);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static Mesh CoerceToMesh(JToken t)");
            sb.AppendLine("        {");
            sb.AppendLine("            var path = t?.Value<string>();");
            sb.AppendLine("            if (string.IsNullOrEmpty(path))");
            sb.AppendLine("                throw new System.ArgumentException(\"Mesh requires an asset path string.\");");
            sb.AppendLine("            return AssetDatabase.LoadAssetAtPath<Mesh>(path);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static GraphicsBuffer CoerceToGraphicsBuffer(JToken t)");
            sb.AppendLine("        {");
            sb.AppendLine("            // Runtime buffer assignment is performed elsewhere; coercion is a no-op here.");
            sb.AppendLine("            return null;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static AnimationCurve CoerceToAnimationCurve(JToken t)");
            sb.AppendLine("        {");
            sb.AppendLine("            // Curves come in via JSON-encoded keyframes; default to a linear 0->1 curve when null.");
            sb.AppendLine("            return AnimationCurve.Linear(0f, 0f, 1f, 1f);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static Gradient CoerceToGradient(JToken t)");
            sb.AppendLine("        {");
            sb.AppendLine("            return new Gradient();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static Matrix4x4 CoerceToMatrix4x4(JToken t)");
            sb.AppendLine("        {");
            sb.AppendLine("            return Matrix4x4.identity;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ─────────────────────────── child dispatch ───────────────────────────
        // ERRATUM P-M2: dispatch coercer per child type FQN, not hardcoded
        // CoerceToFloat. Known leaves resolve directly; nested compound types
        // resolve to the matching CoerceTo<ShortName> method emitted earlier
        // in topological order. Returns null when the type has no coercer
        // available (caller must emit a stub assignment).
        private static string DispatchCoercer(string childTypeFqn,
                                               HashSet<string> availableCompoundFqns)
        {
            switch (childTypeFqn)
            {
                case "System.Single": return "CoerceToFloat";
                case "System.Double": return "CoerceToFloat";
                case "System.Int32":  return "CoerceToInt";
                case "System.UInt32": return "CoerceToUInt";
                case "System.Boolean": return "CoerceToBool";
                case "System.String": return "CoerceToString";
                case "UnityEngine.Texture2D": return "CoerceToTexture2D";
                case "UnityEngine.Texture3D": return "CoerceToTexture3D";
                case "UnityEngine.Cubemap": return "CoerceToCubemap";
                case "UnityEngine.Mesh": return "CoerceToMesh";
                case "UnityEngine.GraphicsBuffer": return "CoerceToGraphicsBuffer";
                case "UnityEngine.AnimationCurve": return "CoerceToAnimationCurve";
                case "UnityEngine.Gradient": return "CoerceToGradient";
                case "UnityEngine.Matrix4x4": return "CoerceToMatrix4x4";
                default:
                    // Compound — only return a method name if we plan to emit it.
                    if (availableCompoundFqns != null && availableCompoundFqns.Contains(childTypeFqn))
                        return "CoerceTo" + ShortNameForMethod(childTypeFqn);
                    return null;
            }
        }

        private static string ShortNameForMethod(string fqn)
        {
            int dot = fqn.LastIndexOf('.');
            string tail = dot >= 0 ? fqn.Substring(dot + 1) : fqn;
            return tail.Replace("+", "_").Replace("`", "_");
        }

        // ─────────────────────────── compound emitter ───────────────────────────
        private static void EmitCompoundCoercer(StringBuilder sb, SlotTypeDescriptor slot,
                                                 HashSet<string> availableCompoundFqns)
        {
            string typeName = slot.TypeFQN.Replace("+", ".");
            string methodName = "CoerceTo" + ShortNameForMethod(slot.TypeFQN);

            sb.AppendLine($"        public static {typeName} {methodName}(JToken t)");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (t == null) throw new System.ArgumentNullException(nameof(t));");
            sb.AppendLine($"            var result = new {typeName}();");
            sb.AppendLine("            if (t.Type == JTokenType.Array)");
            sb.AppendLine("            {");
            sb.AppendLine("                var arr = (JArray)t;");
            for (int i = 0; i < slot.Children.Count; i++)
            {
                var child = slot.Children[i];
                string coercer = DispatchCoercer(child.ChildTypeFQN, availableCompoundFqns);
                if (coercer == null)
                {
                    sb.AppendLine($"                // {child.Name}: no coercer registered for {child.ChildTypeFQN} (skipped)");
                }
                else
                {
                    sb.AppendLine($"                if (arr.Count > {i}) result.{child.Name} = {coercer}(arr[{i}]);");
                }
            }
            sb.AppendLine("            }");
            sb.AppendLine("            else if (t.Type == JTokenType.Object)");
            sb.AppendLine("            {");
            sb.AppendLine("                var obj = (JObject)t;");
            foreach (var child in slot.Children)
            {
                string coercer = DispatchCoercer(child.ChildTypeFQN, availableCompoundFqns);
                if (coercer == null)
                {
                    sb.AppendLine($"                // {child.Name}: no coercer registered for {child.ChildTypeFQN} (skipped)");
                }
                else
                {
                    sb.AppendLine($"                if (obj[\"{child.Name}\"] != null) result.{child.Name} = {coercer}(obj[\"{child.Name}\"]);");
                }
            }
            sb.AppendLine("            }");
            sb.AppendLine("            else");
            sb.AppendLine("            {");
            sb.AppendLine($"                throw new System.InvalidCastException($\"Cannot coerce {{t.Type}} to {typeName}\");");
            sb.AppendLine("            }");
            sb.AppendLine("            return result;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }
}
