// Packages/com.spiralingstudio.mcp.vfxgraph/Editor/Generation/Emitters/OverridesEmitter.cs
// Phase 3 task 3A-7: emits Editor/Generated/VfxOverrides.g.cs.
//
// Phase-3 stub: returns null for every lookup. Phase 5 populates Quirks.yaml
// + Hints.yaml; this emitter then reads those files and bakes their entries
// into the generated dictionaries. Until then the override layer is empty
// but the API surface is stable so the kernel can already call into it.
using System.Text;

namespace SpiralingStudio.VfxMcp.Generation
{
    internal sealed class OverridesEmitter
    {
        public string Emit(CatalogIR ir)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Do not edit. Regenerate via Tools/VFX MCP/Regenerate Catalog.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace SpiralingStudio.VfxMcp.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Override layer (phase 5 will populate from Quirks.yaml + Hints.yaml).");
            sb.AppendLine("    /// All lookups currently return null; the kernel must fall back to the");
            sb.AppendLine("    /// generated catalog or default behaviour when null is returned.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    internal static class VfxOverrides");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>Resolve a short-name collision to a single FQN, or null when no override exists.</summary>");
            sb.AppendLine("        public static string ResolveCollision(string shortName) => null;");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>Look up a hint template for an error code, or null when none is registered.</summary>");
            sb.AppendLine("        public static string GetHint(string errorCode) => null;");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>Look up a quirk-defined alias to its raw catalog entry, or null when none is registered.</summary>");
            sb.AppendLine("        public static string ResolveAlias(string alias) => null;");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
