// Packages/com.spiralingstudio.mcp.vfxgraph/Editor/Generation/Emitters/SchemasEmitter.cs
// Phase 3 task 3A-6: emits Editor/Generated/VfxToolSchemas.g.cs.
//
// Stores per-tool action enum strings derived from CatalogIR. The phase 4
// tool classes use these to validate incoming params: e.g. vfx_node.add must
// receive a 'type' string drawn from VfxToolSchemas.VfxNode_AddTypeEnum.
//
// We emit raw newline-delimited strings (one per FQN) — phase 4 callers
// split on '\n' to get the enum members. JSON-with-escapes is intentionally
// avoided so the diff for a regenerated catalog stays one-line-per-type.
using System.Linq;
using System.Text;

namespace SpiralingStudio.VfxMcp.Generation
{
    internal sealed class SchemasEmitter
    {
        public string Emit(CatalogIR ir)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Do not edit. Regenerate via Tools/VFX MCP/Regenerate Catalog.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace SpiralingStudio.VfxMcp.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Generated tool action / type enums consumed by phase 4 tool classes.");
            sb.AppendLine("    /// Each *_TypeEnum is the newline-delimited list of valid type FQNs for");
            sb.AppendLine("    /// the corresponding action; tool classes split on '\\n' before validation.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    internal static class VfxToolSchemas");
            sb.AppendLine("    {");

            EmitTypeEnum(sb, "VfxNode_AddTypeEnum", "vfx_node.add",
                ir.Operators.Select(o => o.TypeFQN));
            EmitTypeEnum(sb, "VfxBlock_AddTypeEnum", "vfx_block.add",
                ir.Blocks.Select(o => o.TypeFQN));
            EmitTypeEnum(sb, "VfxContext_AddTypeEnum", "vfx_context.add",
                ir.Contexts.Select(o => o.TypeFQN));
            EmitTypeEnum(sb, "VfxParameter_AddTypeEnum", "vfx_node.add_parameter",
                ir.Parameters.Select(o => o.TypeFQN));
            EmitTypeEnum(sb, "VfxSubgraphOperator_AddTypeEnum", "vfx_subgraph.add_ref(operator)",
                ir.SubgraphOperators.Select(o => o.TypeFQN));
            EmitTypeEnum(sb, "VfxSubgraphBlock_AddTypeEnum", "vfx_subgraph.add_ref(block)",
                ir.SubgraphBlocks.Select(o => o.TypeFQN));
            EmitTypeEnum(sb, "VfxSubgraphContext_AddTypeEnum", "vfx_subgraph.add_ref(context)",
                ir.SubgraphContexts.Select(o => o.TypeFQN));

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void EmitTypeEnum(StringBuilder sb, string field, string actionDescription,
                                          System.Collections.Generic.IEnumerable<string> fqns)
        {
            var ordered = fqns
                .OrderBy(s => s, System.StringComparer.Ordinal)
                .ToList();
            sb.AppendLine($"        // {actionDescription} — {ordered.Count} types");
            sb.AppendLine($"        public static readonly string {field} = string.Join(\"\\n\", new string[]");
            sb.AppendLine("        {");
            foreach (var fqn in ordered)
                sb.AppendLine($"            \"{fqn}\",");
            sb.AppendLine("        });");
            sb.AppendLine();
        }
    }
}
