// Packages/com.spiralingstudio.mcp.vfxgraph/Editor/Generation/Emitters/SubgraphWrappersEmitter.cs
// Phase 3 task 3A-5: emits Editor/Generated/VfxSubgraphWrappers.g.cs.
//
// Provides BindAsset(VFXModel refModel, string assetPath) which loads the
// asset at assetPath and assigns it to the refModel's m_Subgraph field via
// UnityEditor.SerializedObject. The field name "m_Subgraph" is identical
// across the three subgraph model types in VFX Graph 17.4 — verified via
// mcp__jcodemunch__search_text against the embedded source:
//
//   Editor/Models/Operators/VFXSubgraphOperator.cs:73
//     protected VisualEffectSubgraphOperator m_Subgraph;
//   Editor/Models/Blocks/VFXSubgraphBlock.cs:14
//     protected VisualEffectSubgraphBlock m_Subgraph;
//   Editor/Models/Contexts/VFXSubgraphContext.cs:16
//     protected VisualEffectAsset m_Subgraph;
//
// The asset *type* differs (operator: .vfxoperator, block: .vfxblock,
// context: .vfx), so we branch on refModel.GetType() to load the correct
// asset class.
using System.Text;

namespace SpiralingStudio.VfxMcp.Generation
{
    internal sealed class SubgraphWrappersEmitter
    {
        public string Emit(CatalogIR ir)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Do not edit. Regenerate via Tools/VFX MCP/Regenerate Catalog.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using UnityEditor;");
            sb.AppendLine("using UnityEditor.VFX;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.VFX;");
            sb.AppendLine();
            sb.AppendLine("namespace SpiralingStudio.VfxMcp.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Subgraph reference helpers. BindAsset assigns the m_Subgraph field");
            sb.AppendLine("    /// of the supplied VFXSubgraphOperator/Block/Context to the asset at");
            sb.AppendLine("    /// assetPath, validating that the asset class matches the model type.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    internal static class VfxSubgraphWrappers");
            sb.AppendLine("    {");

            sb.AppendLine("        public static void BindAsset(VFXModel refModel, string assetPath)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (refModel == null)");
            sb.AppendLine("                throw new System.ArgumentNullException(nameof(refModel));");
            sb.AppendLine("            if (string.IsNullOrEmpty(assetPath))");
            sb.AppendLine("                throw new System.ArgumentException(\"assetPath must be non-empty.\", nameof(assetPath));");
            sb.AppendLine();
            sb.AppendLine("            // The asset class differs per model type. We load via the");
            sb.AppendLine("            // generic Object loader and verify the runtime type matches the");
            sb.AppendLine("            // expected concrete subgraph asset class — this avoids needing");
            sb.AppendLine("            // an InternalsVisibleTo for the runtime assembly that owns");
            sb.AppendLine("            // VisualEffectSubgraphOperator/Block/Context, which are not on");
            sb.AppendLine("            // the public API surface in 17.4.");
            sb.AppendLine("            var asset = AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(assetPath);");
            sb.AppendLine("            if (asset == null)");
            sb.AppendLine("                throw new System.IO.FileNotFoundException(");
            sb.AppendLine("                    $\"Subgraph asset not found at {assetPath}.\");");
            sb.AppendLine();
            sb.AppendLine("            string assetTypeName = asset.GetType().Name;");
            sb.AppendLine("            if (refModel is VFXSubgraphOperator)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (assetTypeName != \"VisualEffectSubgraphOperator\")");
            sb.AppendLine("                    throw new System.InvalidOperationException(");
            sb.AppendLine("                        $\"VFXSubgraphOperator expected a .vfxoperator asset (VisualEffectSubgraphOperator); got {assetTypeName} at {assetPath}.\");");
            sb.AppendLine("            }");
            sb.AppendLine("            else if (refModel is VFXSubgraphBlock)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (assetTypeName != \"VisualEffectSubgraphBlock\")");
            sb.AppendLine("                    throw new System.InvalidOperationException(");
            sb.AppendLine("                        $\"VFXSubgraphBlock expected a .vfxblock asset (VisualEffectSubgraphBlock); got {assetTypeName} at {assetPath}.\");");
            sb.AppendLine("            }");
            sb.AppendLine("            else if (refModel is VFXSubgraphContext)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (!(asset is VisualEffectAsset))");
            sb.AppendLine("                    throw new System.InvalidOperationException(");
            sb.AppendLine("                        $\"VFXSubgraphContext expected a .vfx asset (VisualEffectAsset); got {assetTypeName} at {assetPath}.\");");
            sb.AppendLine("            }");
            sb.AppendLine("            else");
            sb.AppendLine("            {");
            sb.AppendLine("                throw new System.InvalidOperationException(");
            sb.AppendLine("                    $\"BindAsset only supports VFXSubgraphOperator/Block/Context — got {refModel.GetType().FullName}.\");");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            var so = new SerializedObject(refModel);");
            sb.AppendLine("            var prop = so.FindProperty(\"m_Subgraph\");");
            sb.AppendLine("            if (prop == null)");
            sb.AppendLine("                throw new System.InvalidOperationException(");
            sb.AppendLine("                    $\"{refModel.GetType().Name} has no m_Subgraph property.\");");
            sb.AppendLine("            prop.objectReferenceValue = asset;");
            sb.AppendLine("            so.ApplyModifiedPropertiesWithoutUndo();");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
