// Packages/com.spiralingstudio.mcp.vfxgraph/Editor/Generation/Emitters/WrappersEmitter.cs
// Phase 3 task 3A-4: emits Editor/Generated/VfxNodeWrappers.g.cs.
//
// Pattern: every operator/block/context/parameter gets one factory entry on
// VfxNodeWrappers.CreateOperator/CreateBlock/CreateContext/CreateParameter
// keyed by its TypeFQN. The factory method delegates to the matching
// VFXModelDescriptor.CreateInstance() — the same path Unity's UI takes when
// the user adds a node from the catalog.
//
// We deliberately do NOT enumerate every type into a giant switch — the
// runtime cost and the IL size make that unattractive at ~600 nodes. Instead
// we walk VFXLibrary at call time and short-circuit on the first FQN match,
// which keeps the generated code under 100 lines and lets us regenerate the
// catalog without rewriting wrappers.
using System.Text;

namespace SpiralingStudio.VfxMcp.Generation
{
    internal sealed class WrappersEmitter
    {
        public string Emit(CatalogIR ir)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Do not edit. Regenerate via Tools/VFX MCP/Regenerate Catalog.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using UnityEditor.VFX;");
            sb.AppendLine();
            sb.AppendLine("namespace SpiralingStudio.VfxMcp.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Generated factories for every catalog node type. Each method walks");
            sb.AppendLine("    /// VFXLibrary.Get*() once and returns a freshly constructed VFXModel of");
            sb.AppendLine("    /// the requested concrete type. Throws ArgumentException for unknown FQNs.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    internal static class VfxNodeWrappers");
            sb.AppendLine("    {");

            sb.AppendLine("        public static VFXOperator CreateOperator(string typeFqn)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (string.IsNullOrEmpty(typeFqn))");
            sb.AppendLine("                throw new System.ArgumentException(\"typeFqn must be non-empty.\", nameof(typeFqn));");
            sb.AppendLine("            foreach (var d in VFXLibrary.GetOperators())");
            sb.AppendLine("                if (d.modelType.FullName == typeFqn)");
            sb.AppendLine("                    return (VFXOperator)d.CreateInstance();");
            sb.AppendLine("            throw new System.ArgumentException($\"Unknown operator type: {typeFqn}\", nameof(typeFqn));");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public static VFXBlock CreateBlock(string typeFqn)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (string.IsNullOrEmpty(typeFqn))");
            sb.AppendLine("                throw new System.ArgumentException(\"typeFqn must be non-empty.\", nameof(typeFqn));");
            sb.AppendLine("            foreach (var d in VFXLibrary.GetBlocks())");
            sb.AppendLine("                if (d.modelType.FullName == typeFqn)");
            sb.AppendLine("                    return (VFXBlock)d.CreateInstance();");
            sb.AppendLine("            throw new System.ArgumentException($\"Unknown block type: {typeFqn}\", nameof(typeFqn));");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public static VFXContext CreateContext(string typeFqn)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (string.IsNullOrEmpty(typeFqn))");
            sb.AppendLine("                throw new System.ArgumentException(\"typeFqn must be non-empty.\", nameof(typeFqn));");
            sb.AppendLine("            foreach (var d in VFXLibrary.GetContexts())");
            sb.AppendLine("                if (d.modelType.FullName == typeFqn)");
            sb.AppendLine("                    return (VFXContext)d.CreateInstance();");
            sb.AppendLine("            throw new System.ArgumentException($\"Unknown context type: {typeFqn}\", nameof(typeFqn));");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public static VFXParameter CreateParameter(string typeFqn)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (string.IsNullOrEmpty(typeFqn))");
            sb.AppendLine("                throw new System.ArgumentException(\"typeFqn must be non-empty.\", nameof(typeFqn));");
            sb.AppendLine("            foreach (var d in VFXLibrary.GetParameters())");
            sb.AppendLine("                if (d.modelType.FullName == typeFqn)");
            sb.AppendLine("                    return (VFXParameter)d.CreateInstance();");
            sb.AppendLine("            throw new System.ArgumentException($\"Unknown parameter type: {typeFqn}\", nameof(typeFqn));");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
